

=== https://www.youtube.com/watch?v=OXGznpKZ_sA[CSS Tutorial - Full Course For Beginners]

https://github.com/gitdagray/css_course[Full source code]

==== Start Here

Type `!` > `ENTER` for Emmet completion for HTML template.

Type `link` > `TAB`

Type `CMD + X` to cut and `CMD + V` to paste.

https://jigsaw.w3.org/css-validator/[W3C CSS Validation Service]

==== Selectors

Keep id selector out CSS as possible.

`h1, h2`: h1 and h2

`h1 h2`: h2 inside h1

Cascading

* Specificity: element < class < id
* Order

https://specificity.keegan.st/[Specificity Calculator]

`nav > a:hover::before`

* 1 https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes[pseudo-classes]: `:hover`
* 2 elements and 1 pseudo-elements: `nav`, `a`, `::before`

`ul#primary-nav li.active`

* 1 ID: `#primary-nav`
* 1 class: `.active`
* 2 elements: `ul`, `li`

==== Colors

https://coolors.co/[Color palettes generator: Coolors.co]

* https://coolors.co/contrast-checker/3e78c0-ffefd5[Poor contrast example]


https://webaim.org/resources/contrastchecker/[WebAIM( Web accessibility in mind) Contrast Checker]

==== Units & Sizes

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units[MDN values and units]

* `rem`: font size of the root element
* `em`: font size of the parent
* `ch`: The advance measure (width) of the glyph "0" of the element's font.

`p*10>lorem`

==== Box Model

[source, css]
----
box-sizing: content-box;
box-sizing: border-box;
----

margin is outside the CSS boxing model and others is decided by `box-sizing`.

Check `computed` tab after opening the inspecting element.

[source,css]
----
 padding: 1.5em 2em 3em 4em;
----

==== Typography

https://fonts.google.com/[Google fonts]

For external font, you need to put its link before your custom css.

==== Styling Links

https://specificity.keegan.st/[a, a:hover a:visited]

* Specificity: `a:hover` = `a:visited` = `a:active` > `a`

The later overrides what stands before, so we should put as

* `a:visited`
* `a:hover`
* `a:active`


`a:focus` for screen readers or something other than mouse.

==== List Styles

==== Mini Project

==== Display

We cannot apply `margin`, `height` to inline element like `span`.

CSS reset:

[source,css]
----
* {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
----

CSS reset.

`margin-line`: margin for left and right.

==== Floats

`div.block` > `ENTER`

`p*5>lorem20` > `TAB`

[source,css]
----
.left {
    float: left;
}
----

Use

[source,css]
----
overflow: auto
----

or

[source,css]
----
display: flow-root
----

==== Columns

Margin collapsing


To avoid `h2` split into two parts

[source,css]
break-inside: avoid;

* Maybe we don't need this anymore?


https://old.unicode-table.com/en/[Unicode table com]

Specificity:

* `.columns p` > `.quote`

==== Position

[source,css]
 position: static;

* Default value for `position` is `static`.


`absolute` has its position to its closest ancestor with position as relative.

`relative` has its position relative to its parent.

`fix` has its position relative to the window even if you scroll.

`sticky` has its position with minimum spacing relative to its parent container even if you scroll.

`z-index` is 0 by default.

[source,css]
 left: -10000px;

* Make things still there for screen reader but make it invisible.

`OPTION + SHIFT + DOWN` to copy selected text and paste below.

==== Flexbox

https://flexboxfroggy.com/[Flexbox froggy]

`SHIFT + OPTION + F`: Format

* `justify-content`

* `align-items`

* `flex-direction`

* `order`

* `align-self`

* `flex-wrap`

* `flex-flow`

* `align-content`

==== Grid Layout

https://cssgridgarden.com/[Grid garden]

`grid-area`

* `grid-row-start`, `grid-column-start`, `grid-row-end`, `grid-column-end`

==== Image

If you set width and height for image in HTML, after you set percentage for width, you should set height as auto to make it responsive.

[source,css]
----
.example img {
    width: 25%;
    height: auto;
}
----

Image are inline element by default.


Make span element nowrap.

[source,css]
----
.nowrap {
    white-space: nowrap;
}
----

[source,css]
----
text-shadow: 2px 2px 5px black;
----

[source,css]
----
 background-color: hsl(0, 0%, 100%, 0.35);
----

* Used as a filter

https://caniuse.com/[CanIUse.com]

* `background-clip`

==== Media Queries

`!` > `TAB`

`CMD + D`: Select next word

`OPTION + SHIFT + DOWN`: Copy selected and paste below

==== Card Project

Select `Show media queries`

==== Pseudo

`is` pseudo selector

Hover your css tag and VS code will show its specificity.

`is` combines the specificity

[source,css]
----
:is(header, footer, .card {
}
----

`where` gives the specificity of 0 0 0

[source,css]
----
:where(header, footer, .card {
}
----

[source,css]
----
.card img[alt] {

}
----

* Select any image that has the `alt` attribute

[source,css]
----
.card img:not([alt]) {
  border: 10px solid red;
}
----


[source,css]
----
.card:nth-child(odd) {
}
----

* Note that `nth-child` specify elements in HTML. If your order is modified by media query, the result may surprise you.

[source,css]
----
.card figcaption::after {
    content: " hello";
}
----

* You cannot select `hello` using the mouse since it's pseudo element.

https://stackoverflow.com/questions/49336584/is-there-a-quick-way-to-delete-an-html-tag-pair-in-vscode[SO: Emmet remove HTML tag pair]

[source,css]
----
.card figcaption::first-letter {
}
----

* You can try other selectors: `first-line`

==== Variable

`div.square*12` > `ENTER`

`CMD + SHIFT + L` > Move cursor to front > paste emoji

[source,css]
----
.square--hightlight {
    --SQUARE-BGCOLOR: cornflowerblue;
}
----

* Redefine the variable

==== Functions

[source,css]
----
{
--FS: min(2.25rem, 3vh);
}
----

* When you change the window height, `vh` changes.


[source,css]
----
 --FS: clamp(1.75rem, 3vh, 2.25rem);
----

[source,css]
----
a:any-link {

}
----

* For either non-visited or visited link

[source,css]
----
filter: brightness(150%);

filter: hue-rotate(180deg);
----

[source,css]
----
grid-template-columns: repeat(4, minmax(100px, 300px));
----

* https://developer.mozilla.org/zh-CN/docs/Web/CSS/minmax[MDN minmax]


==== Animations

Use `TAB` to tab through the pages

==== Organization

`CMD + SHIFT + P`: Sort ascending

Naming

* BEM: Block(component), element, modifier
* For example, `header__btn--lean`

