

=== https://www.youtube.com/watch?v=OXGznpKZ_sA[CSS Tutorial - Full Course For Beginners]

https://github.com/gitdagray/css_course[Full source code]

==== Start Here

Type `!` > `ENTER` for Emmet completion for HTML template.

Type `link` > `TAB`

Type `CMD + X` to cut and `CMD + V` to paste.

https://jigsaw.w3.org/css-validator/[W3C CSS Validation Service]

==== Selectors

Keep id selector out CSS as possible.

`h1, h2`: h1 and h2

`h1 h2`: h2 inside h1

Cascading

* Specificity: element < class < id
* Order

https://specificity.keegan.st/[Specificity Calculator]

`nav > a:hover::before`

* 1 https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes[pseudo-classes]: `:hover`
* 2 elements and 1 pseudo-elements: `nav`, `a`, `::before`

`ul#primary-nav li.active`

* 1 ID: `#primary-nav`
* 1 class: `.active`
* 2 elements: `ul`, `li`

==== Colors

https://coolors.co/[Color palettes generator: Coolors.co]

* https://coolors.co/contrast-checker/3e78c0-ffefd5[Poor contrast example]


https://webaim.org/resources/contrastchecker/[WebAIM( Web accessibility in mind) Contrast Checker]

==== Units & Sizes

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units[MDN values and units]

* `rem`: font size of the root element
* `em`: font size of the parent
* `ch`: The advance measure (width) of the glyph "0" of the element's font.

`p*10>lorem`

==== Box Model

[source, css]
----
box-sizing: content-box;
box-sizing: border-box;
----

margin is outside the CSS boxing model and others is decided by `box-sizing`.

Check `computed` tab after opening the inspecting element.

[source,css]
----
 padding: 1.5em 2em 3em 4em;
----

==== Typography

https://fonts.google.com/[Google fonts]

For external font, you need to put its link before your custom css.

==== Styling Links

https://specificity.keegan.st/[a, a:hover a:visited]

* Specificity: `a:hover` = `a:visited` = `a:active` > `a`

The later overrides what stands before, so we should put as

* `a:visited`
* `a:hover`
* `a:active`


`a:focus` for screen readers or something other than mouse.

==== List Styles

==== Mini Project

==== Display

We cannot apply `margin`, `height` to inline element like `span`.

CSS reset:

[source,css]
----
* {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
----

CSS reset.


`margin-line`: margin for left and right.