

=== https://www.youtube.com/watch?v=kUMe1FH4CHE[Learn HTML - Full Tutorial for Beginners (2022)]

https://github.com/gitdagray/html_course[Full Code]

https://chromewebstore.google.com/detail/dark-new-tab/kcphhkbdlfggickaoeiahdcfhagfbajl[Dark new tab]

==== Getting Started

Download https://code.visualstudio.com/Download#[VS Code]

* Install extension `Live Server`
   - Right click `Open with Live Server`

Edit `index.html` as

[source,html]
----
include::01_lesson/index.html.1.html[]
----

Use the https://validator.w3.org/[W3C Markup Validation Service] to check the above html and modify as follows:

[source,html]
----
include::01_lesson/index.html.2.html[]
----
<1> Add document type as `html`
<2> Specify language as `en`

==== Head Elements

[source,html]
----
include::02_lesson/index.html.1.html[]
----
<1> Add icon as `html5.png`
<2> Move stylesheet to `main.css`

`main.css`
[source,css]
----
include::02_lesson/main.css[]
----

==== Text Basics

https://stackoverflow.com/questions/40155875/how-can-i-do-tag-wrapping-in-visual-studio-code[Wrap]

* `Cmd` + `Shift` + `P`
* Emmet: Wrap with Abbreviation
* e.g. `abbr` > `Enter` > your title content

==== List Types

Visual select you text > `Cmd + D` to select next same visual element > `Cmd + D` to select next same visual element > Enter `<li>`

Install `Prettier Code Formatter`.

* `Cmd + Shift + P` > `Format document`


https://stackoverflow.com/questions/50975264/prettier-settings-for-vscode[SO prettier settings for VSCode]
Edit `~/Library/Application\ Support/Code/User/settings.json`

[source,json]
----
{
    "workbench.colorTheme": "Default Dark Modern",
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.formatOnSave": true,
    "prettier.requireConfig": true,
    "prettier.prettierPath": ".prettierrc.json"
}
----

* `settings.json` path for VSCode: e.g. `~/.nodebrew/current/lib/node_modules/prettier`

Under your project root, edit `.prettierrc.json`. For more options, check https://prettier.io/docs/en/options.html[here]. https://stackoverflow.com/questions/58583840/unable-to-set-tab-width-to-4-in-prettier[SO]

[source,json]
----
 {
   "files.trimTrailingWhitespace": true,
   "printWidth": 80,
   "tabWidth": 4,
   "useTabs": false
 }
----

* Note that after you save `.prettierrc.json`, you need to reopen the file to make the plugin reload for the change.

==== Add Links

Type `lorem*1` for Emmet Abbreviation for https://en.wikipedia.org/wiki/Lorem_ipsum[Lorem ipsum]

Use `CMD + <-` for going back on the browsing stack.

Use `target="_blank"` to open the link in a new tab.

==== Add Images

Type `img` then `TAB` in VS Code for auto-completion.

Provide `width` and `height` for `img` to preserve spacing before loading to avoid browser layout shift.

Set attribute as `loading="lazy"` to load image only when the image is about to show.

* `br*150` is not enough for Chrome now, set it as `br*300` https://stackoverflow.com/questions/57753240/native-lazy-loading-loading-lazy-not-working-even-with-flags-enabled[SO]


Resources

* https://via.placeholder.com/640x480[via.placeholder.com]

* https://unsplash.com/[Unsplash]

* https://www.pexels.com/[Pexels]

* https://gratisography.com/[Gratisography]

* https://pixabay.com/[Pixabay]

* https://www.canva.com/[Canva]

* https://tinypng.com/[TinyPNG]

==== Semantic Tags

https://www.w3schools.com/html/html5_semantic_elements.asp[W3Schools semantic elements]

Used now

* figcaption
* figure
* nav
* section
* (hr)

To add

* header
* main
* footer

[source,html]
----
<nav aria-labelledby="primary-navigation">
    <h2 id="" primary-navigation>Primary Navigation</h2>
    <ul>
        <li><a href="#html">Learn HTML</a></li>
        <li><a href="#vacation">Planning a Vacation</a></li>
   </ul>
</nav>
----

Use `CMD+D` to change closed tag simultaneously. https://stackoverflow.com/questions/51803668/visual-studio-code-how-to-automatically-change-the-matching-closing-tag[SO]

Select your text > `CMD + SHIFT + P` > Choose `Emmet` plugin > Type `section`.

Type `aside` > `TAB`

[source,html]
----
<aside>
    <details>
        <summary>
            Guess the <mark>number of hours</mark> I code per day
        </summary>
        <p>I start at <time datetime="08:00">8pm</time> and I write code for <time datetime="PT3H">3 hours</time> every morning.
        </p>
    </details>
</aside>
----

Avoid:

* `div`: divider without semantic meaning
* `span`: no semantic meaning

Install https://chromewebstore.google.com/detail/html5-outliner/afoibpobokebhgfnknfndkgemglggomo[HTML5 outliner]