

=== https://www.youtube.com/watch?v=kUMe1FH4CHE[Learn HTML - Full Tutorial for Beginners (2022)]

https://github.com/gitdagray/html_course[Full Code]

https://chromewebstore.google.com/detail/dark-new-tab/kcphhkbdlfggickaoeiahdcfhagfbajl[Dark new tab]

==== Lesson 01

Download https://code.visualstudio.com/Download#[VS Code]

* Install extension `Live Server`
   - Right click `Open with Live Server`

Edit `index.html` as

[source,html]
----
include::01_lesson/index.html.1.html[]
----

Use the https://validator.w3.org/[W3C Markup Validation Service] to check the above html and modify as follows:

[source,html]
----
include::01_lesson/index.html.2.html[]
----
<1> Add document type as `html`
<2> Specify language as `en`

==== Lesson 02

[source,html]
----
include::02_lesson/index.html.1.html[]
----
<1> Add icon as `html5.png`
<2> Move stylesheet to `main.css`

`main.css`
[source,css]
----
include::02_lesson/main.css[]
----

==== Lesson 03

https://stackoverflow.com/questions/40155875/how-can-i-do-tag-wrapping-in-visual-studio-code[Wrap]

* `Cmd` + `Shift` + `P`
* Emmet: Wrap with Abbreviation
* e.g. `abbr` > `Enter` > your title content

==== Lesson 04

Visual select you text > `Cmd + D` to select next same visual element > `Cmd + D` to select next same visual element > Enter `<li>`

Install `Prettier Code Formatter`.

* `Cmd + Shift + P` > `Format document`


https://stackoverflow.com/questions/50975264/prettier-settings-for-vscode[SO prettier settings for VSCode]
Edit `~/Library/Application\ Support/Code/User/settings.json`

[source,json]
----
{
    "workbench.colorTheme": "Default Dark Modern",
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.formatOnSave": true,
    "prettier.requireConfig": true,
    "prettier.prettierPath": ".prettierrc.json"
}
----

Under your project root, edit `.prettierrc.json`
[source,json]
----
{
  "files.trimTrailingWhitespace": true
}
----

`settings.json` path for VSCode: e.g. `~/.nodebrew/current/lib/node_modules/prettier`