=== Basic Types

==== Types

The https://www.typescripttutorial.net/typescript-tutorial/typescript-object-type/[primitive types] in TypeScript:

* number, bigint
* string
* boolean
* null, undefined
* symbol

Non-primitive type is of type `object`.

To support DOM manipulation in the following example,

Add `tsconfig.json` for

[source,json]
----
{
  // ...
  "compilerOptions": {
    "lib": [
      "DOM"
    ]
  }
}
----

[source,javascript]
----
include::heading.ts[]
----

[source]
----
include::heading.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-type-annotations/[Type Annotations]

[source,javascript]
----
include::annotation.ts[]
----
<1> There should be error here, but the compiler passes it. There may be compiler options to set stricter checking.

[source]
----
include::annotation.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-type-inference/[Type Inference]

link:./TypeScriptTutorialNet/BasicTypes/inference.ts[inference.ts]

[source,javascript]
----
include::inference.ts[]
----

[source,bash]
$ npx tsc -d inference.ts

link:./TypeScriptTutorialNet/BasicTypes/inference.d.ts[inference.d.ts]

[source]
----
include::inference.d.ts[]
----

==== https://typescripttutorial.net/typescript-tutorial/typescript-number/[Number]

Javascript numbers:

* `number`: floating point
* `bigint`: big integers


[source,javascript]
----
include::number.ts[]
----
<1> For your `tsconfig.json`, you need to set target greater or equal to `es2020` or it will report `error TS2737: BigInt literals are not available when targeting lower than ES2020`.

[source]
----
include::number.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-string/[String]

[source,javascript]
----
include::string.ts[]
----

[source,javascript]
----
include::string.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-boolean/[Boolean]

[source,javascript]
----
include::boolean.ts[]
----

[source,javascript]
----
include::boolean.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-object-type/[Object]

https://stackoverflow.com/questions/72004882/asciidoctor-how-to-layout-two-code-blocks-side-by-side[Side-by-side SO]

[cols="a,a", options="header"]
|===
^.^| Source
^.^| Output

|
[source,typescript]
----
include::object.ts[]
----

|
[source]
----
include::object.ts.log[]
----
|===


==== https://www.typescripttutorial.net/typescript-tutorial/typescript-array-type/[Array]

[cols="a,a", options="header"]
|===
^.^| Source
^.^| Output

|
[source,typescript]
----
include::array.ts[]
----

|
[source]
----
include::array.ts.log[]
----
|===

[source,typescript]
----
include::array.d.ts[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-tuple/[Tuple]

[cols="a,a", options="header"]
|===
^.^| Source
^.^| Output

|
[source,typescript]
----
include::tuple.ts[]
----

|
[source]
----
include::tuple.ts.log[]
----
|===

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-enum/[Enum]

[cols="a,a", options="header"]
|===
^.^| Source
^.^| Output

|
[source,typescript]
----
include::enum.ts[]
----

|
[source]
----
include::enum.ts.log[]
----
|===

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-any-type/[Any]

[cols="a,a", options="header"]
|===
^.^| Source
^.^| Output

|
[source,typescript]
----
include::any.ts[]
----

|
[source]
----
include::any.ts.log[]
----
|===

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-void-type/[void]


[source,typescript]
----
include::void.ts[lines=3..]
----
<1> It won't compile if `--strictNullChecks` is true in `tsconfig.json`

[source]
----
include::void.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-never-type/[never]

[source,typescript]
----
include::never.ts[]
----

[source]
----
include::never.d.ts[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-union-type/[union]


[source,typescript]
----
include::union.ts[]
----

[source]
----
include::union.ts.log[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-type-aliases/[Type Alias]

[source,typescript]
----
include::alias.ts[]
----

[source]
----
include::alias.d.ts[]
----

==== https://www.typescripttutorial.net/typescript-tutorial/typescript-string-literal-types/[Literal Types]


[source,typescript]
----
include::literal.ts[]
----

[source]
----
include::literal.ts.log[]
----

[source]
----
include::literal.d.ts[]
----
