.PHONY: download

all: download

download: html5.png

html5.png:
	# https://github.com/gitdagray/html_course/blob/main/02_lesson/html5.png?raw=true
	curl -LO https://raw.githubusercontent.com/gitdagray/html_course/5632f3289a27e991c9132c2798e59a06472c3475/02_lesson/html5.png
